### PR TITLE
fix bug in readRnxObsB

### PR DESCRIPTION
**Pull request by FlowLoveV**
The original readRnxObsB function can only read the observation data of the first epoch, but cannot read the observation data of subsequent epochs. After modification, it can work normally.

### CODE REVIEW

**Comment by polytopes-design** [comment]
It appears you must be testing with a non-conforming rinex file. Could you please provide your rinex file to assess.

**Comment by FlowLoveV** [comment]
[test_file.zip](https://github.com/user-attachments/files/17271907/test_file.zip)

**Comment by polytopes-design** [comment]
Running the existing pea using one of the example configurations with minor changes shows that all valid epochs are read as expected. There are warnings and other messages due to missing ephemerides, but all observations are processed as expected

Portions of the output follow:
```
Starting epoch #1
Synced 1 receivers...
...
estpos: lack of valid measurements ns=0 on ALAC after 0 iterations. (has 40 total observations)
...
Starting epoch #2
Synced 1 receivers...
...
estpos: lack of valid measurements ns=0 on ALAC after 0 iterations. (has 40 total observations)
...
Starting epoch #3
Synced 0 receivers...
...
Starting epoch #28
Synced 1 receivers...
...
estpos: lack of valid measurements ns=0 on ALAC after 0 iterations. (has 39 total observations)
```
Which accounts for all of the observations in the file provided.

Perhaps you are using the function outside of normal `pea` usage, and expecting it to read all of the observations into a vector at once?
This is not the behaviour we use for observation streams in ginan. 

Ginan is designed to be able to be used in real-time or post-processed mode, but both act the same when dealing with observations. i.e. at a given epoch - request all relevant data from the observation stream for that epoch.

To extract all data from the rinex file, the function needs to be called multiple times.
We open and close files as required, as we have previously hit limitations with too many open files.
The `FileState` class is used to maintain the position in the file, and each epoch the function is called by the relevant parsing functions.

This PR will likely cause issues under different circumstances.

**Comment by FlowLoveV** [comment]
I did only use the relevant code of the rinex reading module in the ginan library, which led to this misunderstanding. Thank you very much for your explanation

**Comment by FlowLoveV** [comment]
I did only use the relevant code of the rinex reading module in the ginan library, which led to this misunderstanding. Thank you very much for your explanation

**Comment by seballgeyer** [comment]
After discussions between the author and some team members, we've determined that this PR attempts to use part of the code in a context for which it wasn't designed. Integrating it into the codebase could lead to significant incompatibilities with the normal behavior of Ginan. Therefore, we will not be proceeding with this PR.

However, we recognize that users may want to leverage some functionality outside of Ginan. We will explore ways to generalize certain functions for broader use in the long term.

**Pull request closed without merging**
